# General Site Global Variables

title               : Evan Yohe Portfolio
author              : "Evan Yohe"
baseurl             : "/"
url                 : "https://evanyohe.github.io"
description         : "Welcome to my portfolio website; come check out all my writings and share all the updates and progress reports on various projects that I am working on."
keywords            : ["portfolio", "blog", "technology", "programming", "software", "developer", "data", "science"]

# Social Links and Variables

twitter_username    : "@evan_yohe"
twitter_link        : "https://twitter.com/evan_yohe"
github_username     : "EvanYohe"
github_link         : "https://github.com/EvanYohe"
linkedin_link       : "https://www.linkedin.com/in/evan-yohe/"

# Default Front Matter Variables

defaults            :
  - scope           :
      path          : ""
    values          :
      layout        :
      title         : 
      description   :
      keywords      :
      autonav       :

#Pagination and Post Rendering Variables
 
paginate            : 5
paginate_path       : "/writings/page:num"
show_drafts         : true
unpublished         : true
future              : true
strict_front_mater  : true

# Build Variables

safe                : false
include             : [".htaccess"]
exclude             : [".sass-cache", ".jekyll-cache", "Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
plugins             :
  - github-pages
  - jekyll-paginate